version: "3.8"

services:
  db:
    container_name: PokeDB_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./local_data/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.0.2

  pgadmin:
    container_name: PokeDB_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      app_net:
        ipv4_address: 192.168.0.3
    volumes:
      - ./local_data/pgadmin_data:/var/lib/pgadmin

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1

volumes:
  postgres_data:
  pgadmin_data:
